/* generated by dfcompiler */
/* ---- Dflat runtime (libc version) ---- */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#ifdef _WIN32
#include <windows.h>
#endif

typedef struct {
  const char* p;   /* UTF-8 bytes, not NUL-terminated */
  uint64_t len;    /* byte length */
} df_string;

static void df_fail(const char* type, const char* msg) {
  fflush(stdout);
  fprintf(stderr, "Unhandled %s: %s\n", type, msg);
  exit(1);
}

static void df_panic(int64_t code) {
  fflush(stdout);
  _Exit((int)code);
}

static void* df_alloc(uint64_t n) {
  void* p = malloc(n ? n : 1);
  if (!p) {
    df_fail("OutOfMemoryException", "out of memory");
  }
  return p;
}

/* ---- strings (never freed yet: ownership comes later) ---- */

static df_string df_str_lit(const char* p, uint64_t len) {
  df_string s = { p, len };
  return s;
}

static df_string df_str_concat(df_string a, df_string b) {
  char* p = (char*)df_alloc(a.len + b.len);
  memcpy(p, a.p, a.len);
  memcpy(p + a.len, b.p, b.len);
  df_string s = { p, a.len + b.len };
  return s;
}

static df_string df_str_from_buf(const char* buf) {
  uint64_t n = strlen(buf);
  char* p = (char*)df_alloc(n);
  memcpy(p, buf, n);
  df_string s = { p, n };
  return s;
}

static bool df_str_eq(df_string a, df_string b) {
  return a.len == b.len && memcmp(a.p, b.p, a.len) == 0;
}

/* character count (UTF-8 code points) */
static uint64_t df_str_chars(df_string s) {
  uint64_t n = 0;
  for (uint64_t i = 0; i < s.len; i++) {
    if (((unsigned char)s.p[i] & 0xC0) != 0x80) {
      n++;
    }
  }
  return n;
}

static df_string df_str_from_i64(int64_t v) {
  char buf[32];
  snprintf(buf, sizeof buf, "%lld", (long long)v);
  return df_str_from_buf(buf);
}

static df_string df_str_from_u64(uint64_t v) {
  char buf[32];
  snprintf(buf, sizeof buf, "%llu", (unsigned long long)v);
  return df_str_from_buf(buf);
}

static df_string df_str_from_bool(bool v) {
  return v ? df_str_lit("true", 4) : df_str_lit("false", 5);
}

static df_string df_str_from_char(uint32_t c) {
  char buf[4];
  uint64_t n;
  if (c > 0x10FFFF || (c >= 0xD800 && c <= 0xDFFF)) {
    c = 0;
  }
  if (c < 0x80) {
    buf[0] = (char)c;
    n = 1;
  } else if (c < 0x800) {
    buf[0] = (char)(0xC0 | (c >> 6));
    buf[1] = (char)(0x80 | (c & 0x3F));
    n = 2;
  } else if (c < 0x10000) {
    buf[0] = (char)(0xE0 | (c >> 12));
    buf[1] = (char)(0x80 | ((c >> 6) & 0x3F));
    buf[2] = (char)(0x80 | (c & 0x3F));
    n = 3;
  } else {
    buf[0] = (char)(0xF0 | (c >> 18));
    buf[1] = (char)(0x80 | ((c >> 12) & 0x3F));
    buf[2] = (char)(0x80 | ((c >> 6) & 0x3F));
    buf[3] = (char)(0x80 | (c & 0x3F));
    n = 4;
  }
  char* p = (char*)df_alloc(n);
  memcpy(p, buf, n);
  df_string s = { p, n };
  return s;
}

/* shortest text that reads back as the same value (like C#) */
static df_string df_str_from_real(double v, int maxDigits, bool isFloat) {
  char buf[64];
  if (isnan(v)) {
    return df_str_lit("NaN", 3);
  }
  if (isinf(v)) {
    return v > 0 ? df_str_lit("\xE2\x88\x9E", 3) : df_str_lit("-\xE2\x88\x9E", 4);
  }
  for (int digits = 1; digits <= maxDigits; digits++) {
    snprintf(buf, sizeof buf, "%.*g", digits, v);
    double back = strtod(buf, NULL);
    if (isFloat ? (float)back == (float)v : back == v) {
      break;
    }
  }
  for (char* c = buf; *c; c++) {
    if (*c == 'e') {
      *c = 'E';
    }
  }
  return df_str_from_buf(buf);
}

static df_string df_str_from_r64(double v) {
  return df_str_from_real(v, 17, false);
}

static df_string df_str_from_r32(float v) {
  return df_str_from_real((double)v, 9, true);
}

/* ---- conversions to bool ---- */

static bool df_rbool(double v) {
  return v != 0 && !isnan(v);
}

/* ---- console ---- */

static void df_console_log(df_string s) {
  fwrite(s.p, 1, (size_t)s.len, stdout);
  fputc('\n', stdout);
}

static void df_console_log_error(df_string s) {
  fflush(stdout);
  fwrite(s.p, 1, (size_t)s.len, stderr);
  fputc('\n', stderr);
}

static void df_init(void) {
#ifdef _WIN32
  SetConsoleOutputCP(CP_UTF8);
#endif
}

/* ---- checked integer division ---- */

#define DF_DIV_SIGNED(T, NAME, MIN) \
  static T df_div_##NAME(T a, T b) { \
    if (b == 0) df_fail("DivisionByZeroException", "division by zero"); \
    if (b == -1) return (T)(0 - (uint64_t)a); \
    return (T)(a / b); \
  } \
  static T df_mod_##NAME(T a, T b) { \
    if (b == 0) df_fail("DivisionByZeroException", "division by zero"); \
    if (b == -1) return 0; \
    return (T)(a % b); \
  }

#define DF_DIV_UNSIGNED(T, NAME) \
  static T df_div_##NAME(T a, T b) { \
    if (b == 0) df_fail("DivisionByZeroException", "division by zero"); \
    return (T)(a / b); \
  } \
  static T df_mod_##NAME(T a, T b) { \
    if (b == 0) df_fail("DivisionByZeroException", "division by zero"); \
    return (T)(a % b); \
  }

DF_DIV_SIGNED(int8_t, i8, INT8_MIN)
DF_DIV_SIGNED(int16_t, i16, INT16_MIN)
DF_DIV_SIGNED(int32_t, i32, INT32_MIN)
DF_DIV_SIGNED(int64_t, i64, INT64_MIN)
DF_DIV_UNSIGNED(uint8_t, u8)
DF_DIV_UNSIGNED(uint16_t, u16)
DF_DIV_UNSIGNED(uint32_t, u32)
DF_DIV_UNSIGNED(uint64_t, u64)

/* ---- saturating casts ---- */

#define DF_SAT_INT(T, NAME, LO, HI) \
  static T df_sat_##NAME##_i(int64_t v) { \
    return v < (int64_t)(LO) ? (T)(LO) : (v > (int64_t)(HI) ? (T)(HI) : (T)v); \
  } \
  static T df_sat_##NAME##_u(uint64_t v) { \
    return v > (uint64_t)(HI) ? (T)(HI) : (T)v; \
  } \
  static T df_sat_##NAME##_r(double v) { \
    if (isnan(v)) return 0; \
    if (v <= (double)(LO)) return (T)(LO); \
    if (v >= (double)(HI)) return (T)(HI); \
    return (T)v; \
  }

DF_SAT_INT(int8_t, i8, INT8_MIN, INT8_MAX)
DF_SAT_INT(int16_t, i16, INT16_MIN, INT16_MAX)
DF_SAT_INT(int32_t, i32, INT32_MIN, INT32_MAX)
DF_SAT_INT(uint8_t, u8, 0, UINT8_MAX)
DF_SAT_INT(uint16_t, u16, 0, UINT16_MAX)
DF_SAT_INT(uint32_t, u32, 0, UINT32_MAX)

static int64_t df_sat_i64_i(int64_t v) { return v; }
static int64_t df_sat_i64_u(uint64_t v) { return v > (uint64_t)INT64_MAX ? INT64_MAX : (int64_t)v; }
static int64_t df_sat_i64_r(double v) {
  if (isnan(v)) return 0;
  if (v <= -9223372036854775808.0) return INT64_MIN;
  if (v >= 9223372036854775807.0) return INT64_MAX;
  return (int64_t)v;
}
static uint64_t df_sat_u64_i(int64_t v) { return v < 0 ? 0 : (uint64_t)v; }
static uint64_t df_sat_u64_u(uint64_t v) { return v; }
static uint64_t df_sat_u64_r(double v) {
  if (isnan(v) || v <= 0) return 0;
  if (v >= 18446744073709551615.0) return UINT64_MAX;
  return (uint64_t)v;
}

/* ---- end of runtime ---- */
/* ---- program ---- */

static uint64_t f_fib(uint64_t v_n);
static int32_t f_square(int32_t v_x);
static void f_greet(df_string v_name);

static uint64_t f_fib(uint64_t v_n) {
  if ((v_n < ((uint64_t)2ULL))) {
    return v_n;
  }
  return ((uint64_t)(f_fib(((uint64_t)(v_n - ((uint64_t)1ULL)))) + f_fib(((uint64_t)(v_n - ((uint64_t)2ULL))))));
}

static int32_t f_square(int32_t v_x) {
  return ((int32_t)(v_x * v_x));
}

static void f_greet(df_string v_name) {
  df_console_log(df_str_concat(df_str_concat(df_str_lit("Hello ", 6), v_name), df_str_lit("!", 1)));
}

int main(int argc, char** argv) {
  (void)argc;
  (void)argv;
  df_init();
  /* Namespace basics */
  f_greet(df_str_lit("world", 5));
  f_greet(df_str_lit("Dflat", 5));
  for (uint64_t v_i = ((uint64_t)0ULL); v_i < ((uint64_t)10ULL); v_i++) {
    df_console_log(df_str_concat(df_str_concat(df_str_concat(df_str_lit("fib(", 4), df_str_from_u64((uint64_t)(v_i))), df_str_lit(") = ", 4)), df_str_from_u64((uint64_t)(f_fib(v_i)))));
  }
  int32_t v_total = ((int32_t)0LL);
  for (int32_t v_i = ((int32_t)1LL); v_i <= ((int32_t)100LL); v_i = ((int32_t)(v_i + ((int32_t)1LL)))) {
    v_total = ((int32_t)(v_total + v_i));
  }
  df_console_log(df_str_concat(df_str_lit("sum 1..100 = ", 13), df_str_from_i64((int64_t)(v_total))));
  int32_t v_count = ((int32_t)0LL);
  while ((v_count < ((int32_t)3LL))) {
    v_count++;
  }
  do {
    v_count--;
  } while ((v_count > ((int32_t)1LL)));
  df_console_log(df_str_concat(df_str_lit("count = ", 8), df_str_from_i64((int64_t)(v_count))));
  int16_t v_big16 = ((int16_t)257LL);
  df_console_log(df_str_concat(df_str_concat(df_str_concat(df_str_lit("(i8)257 = ", 10), df_str_from_i64((int64_t)(df_sat_i8_i((int64_t)(v_big16))))), df_str_lit(", [i8]257 = ", 12)), df_str_from_i64((int64_t)(((int8_t)(uint16_t)(v_big16))))));
  double v_huge = (1E+300);
  df_console_log(df_str_concat(df_str_lit("(i32)1e300 = ", 13), df_str_from_i64((int64_t)(df_sat_i32_r((double)(v_huge))))));
  double v_x = (2.0);
  df_console_log(df_str_concat(df_str_lit("sqrt(2) = ", 10), df_str_from_r64(sqrt(v_x))));
  df_console_log(df_str_concat(df_str_concat(df_str_concat(df_str_lit("pi = ", 5), df_str_from_r64((3.141592653589793))), df_str_lit(", lerp = ", 9)), df_str_from_r64(((0.0) + ((10.0) - (0.0)) * (0.25)))));
  df_console_log(df_str_concat(df_str_from_i64((int64_t)(((int32_t)(((int32_t)1LL) + ((int32_t)2LL))))), df_str_lit("a", 1)));
  df_console_log(df_str_concat(df_str_from_char(((uint32_t)97u)), df_str_from_char(((uint32_t)98u))));
  df_console_log(df_str_concat(df_str_lit("square(12) = ", 13), df_str_from_i64((int64_t)(f_square(((int32_t)12LL))))));
  uint32_t v_smile = ((uint32_t)128512u);
  df_console_log(df_str_concat(df_str_lit("smile ", 6), df_str_from_char(v_smile)));
  df_string v_word = df_str_lit("h\303\251llo", 6);
  df_console_log(df_str_concat(df_str_concat(df_str_concat(df_str_concat(df_str_concat(v_word, df_str_lit(" has ", 5)), df_str_from_u64((uint64_t)(df_str_chars(v_word)))), df_str_lit(" chars and ", 11)), df_str_from_u64((uint64_t)(((v_word).len)))), df_str_lit(" bytes", 6)));
  df_console_log(df_str_lit("literal braces: {ok}", 20));
  bool v_flag = true;
  if ((v_flag && (v_total > ((int32_t)5000LL)))) {
    df_console_log(df_str_lit("big total", 9));
  } else if ((v_total > ((int32_t)100LL))) {
    df_console_log(df_str_lit("medium total", 12));
  } else {
    df_console_log(df_str_lit("small total", 11));
  }
  for (int32_t v_a = ((int32_t)0LL); v_a < ((int32_t)5LL); v_a++) {
    for (int32_t v_b = ((int32_t)0LL); v_b < ((int32_t)5LL); v_b++) {
      if ((((int32_t)(v_a * v_b)) == ((int32_t)6LL))) {
        goto lbl_Found;
      }
    }
  }
  lbl_Found: ;
  df_console_log(df_str_lit("found a * b == 6", 16));
  int32_t v_zero = ((int32_t)0LL);
  df_console_log(df_str_lit("dividing by zero...", 19));
  int32_t v_boom = df_div_i32(((int32_t)10LL), v_zero);
  df_console_log(df_str_concat(df_str_lit("not reached ", 12), df_str_from_i64((int64_t)(v_boom))));
  return 0;
}
